Postgres repository
andreyDelay/currency-exchngr pull request #1
Opened 2022-05-05 06:26 UTC by andreyDelay

2022-05-05 13:03 UTC, kegisa requested changes

2022-05-05 13:03 UTC, kegisa commented on docker-compose.yml
> +  exchanger:
depends on не нужен?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    public ResponseEntity<ConvertedCurrencyDto> convert(
Здесь обязаетльно responseentity?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +        return new ResponseEntity<>(convertedCurrencyDto, HttpStatus.OK);
status можнго задать без респонс энтити

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/model/BaseEntity.java
> +public class BaseEntity {
для чего это?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/model/CurrencyRate.java
> +@Setter
обычно data сразу лепится на энтити класс

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/model/CurrencyRate.java
> +    private String charCode;
почему так отличаются названрия в таблице и в модельке?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/repository/DataBaseCurrencyRepository.java
> +	@Query(value = "SELECT cr FROM CurrencyRate cr WHERE cr.charCode = ?1")
зачем здесь query?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/repository/DataBaseCurrencyRepository.java
> +public interface DataBaseCurrencyRepository extends JpaRepository<CurrencyRate, String> {
CRUD repository недостаточно?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/CurrencyService.java
> +public interface CurrencyService extends GenericService<CurrencyRate, String> {
лишняя абстракция, достаточно интерфейса

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/GenericService.java
> +public interface GenericService<T, V> {
Та самая лишняя абстракция

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
> +@Service(value = "DB-oriented-service")
без value =  разве нельзя?

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
> +public class DataBaseCurrencyServiceImpl implements CurrencyService {
Транзакционность лучше указывать явно

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/ExchangeCurrencyServiceImpl.java
> +    @Qualifier(value = "DB-oriented-service")
Вопрос по value = аналогично предыдщуему

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/ExchangeCurrencyServiceImpl.java
> +        if (targetCurrencyData == null) {
Objects.isNull есть такой метод, лучше его юзать

2022-05-05 13:03 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/ExchangeCurrencyServiceImpl.java
> +            throw new RuntimeException("Currency code not found");
Попробуй чтобы currencySerivce возвращал optional(лучше чтобы репозиторйи который он использует)

2022-05-05 13:03 UTC, kegisa commented on src/main/resources/db/changelog/v-1.0/db.changelog-1.0.yml
> +          - sqlFile:
давай без sql тут просто нужно одну табличку создать пиши сразу на yml

2022-05-05 13:03 UTC, kegisa commented on src/main/resources/db/changelog/v-1.0/sql/1.0-create-currency_info-table.sql
> +create table if not exists currency_info(
этого файла соответсвенно не будет когда на yml напишешь

2022-05-05 13:03 UTC, kegisa commented on src/main/resources/liquibase.properties
> +changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
это все нетут должно быть , посмотри как юзать liquibase в спринге буте, отдельно ничего выносить не нужно

2022-05-05 16:41 UTC, kegisa requested changes

2022-05-05 16:41 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/repository/DataBaseCurrencyRepository.java
> +public interface DataBaseCurrencyRepository extends CrudRepository<CurrencyRate, String> {
Почему String? айдишник же лонг

2022-05-06 09:42 UTC, kegisa requested changes

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    @PostMapping("/")
"/" вроде можно убрать?

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +        currencyService.save(currencyRateDto);
при создании отдавай dto которую создал

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    @ResponseStatus(HttpStatus.OK)
возращай 204 при успешном удалении

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    @PutMapping("/")
посмотри вроде при обновлении в rest принято также в  path variable передавать айдишник

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    public CurrencyRateDto getCurrency(@Valid @Pattern(regexp = "[A-Z]{3}")
раздве здесь у тебя работает pattern ? проверь плиз вылетает ли ошибка?

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/CurrencyService.java
> +    CurrencyRateDto findById(String charCode);
id  у тебя же лонг, причем тут charcode?

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
> +    @Transactional(readOnly = true)
Хороший практиков является указывтаь рид онли над классом, а там где не рид онли уже над методом

2022-05-06 09:42 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Not found"));
Создай свой тип ислючений что то вроде RateNotFoundException

2022-05-06 09:42 UTC, kegisa commented on src/main/resources/db/changelog/v-1.0/db.changelog-1.0.yml
> +                  type: integer
в модельке long, это норм?

2022-05-06 09:42 UTC, kegisa commented on src/main/resources/db/changelog/v-1.0/db.changelog-1.0.yml
> +                  name: charcode
Здесь не кэмел кейском пиши а снейккейсом char_code, в модельке при этом кэмелкейсом, хибернейт должен сам будет понять что это именно та колонка

2022-05-06 09:42 UTC, kegisa commented on src/main/resources/db/changelog/v-1.0/db.changelog-1.2.yml
> +            sql: select count(*) from public.currency_info
info выглядит стремновато укажи как есть, что  в этом таблице хранится?

2022-05-10 09:10 UTC, andreyDelay commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    public CurrencyRateDto getCurrency(@Valid @Pattern(regexp = "[A-Z]{3}")
Паттерн работает, но так и не разобрался пока что почему RequestBody пропускает c невалидным JSON.
Например с лишним полем "smth"
`
{
  "charCode": "OAC",
  "value": 1,
  "somth": 25
}
`
Возвращая при этом 201-й код, CREATED
`{
  "charCode": "OAC",
  "value": 1
}`

2022-05-10 13:01 UTC, kegisa requested changes

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +                                          @Valid @Pattern(regexp = "[A-Z]{3}") @PathVariable String charCode) {
Валидация работает?

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/dto/UpdateCurrencyDto.java
> +	private double value;
notnull здесь не надо?

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/CurrencyService.java
> +    CurrencyRateDto findById(String charCode);
Остается также findById но передаеь ты charcode

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
>          repository.findAll().forEach(value ->
ты так сделал потому что там iterable? сделай так чтобы репо возвращал list , здесь не надо по циклу бегать.

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
>          CurrencyRate currencyRate = byCharCode
мне кажется здесь можно в одну строчку это сделать, сразу CurrencyRate currencyRate = repository.findByCharCode(charCode).orElseThrow(() -> new RuntimeException("Not found"));

2022-05-10 13:01 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
>          CurrencyRate currencyRate = targetCurrency
здесь навреное ifPresentOrElse попробуй

2022-05-10 13:04 UTC, kegisa commented on src/main/java/com/andrey/currencyexchgr/controller/CurrencyController.java
> +    public CurrencyRateDto getCurrency(@Valid @Pattern(regexp = "[A-Z]{3}")
так и должнго быть

2022-05-10 14:07 UTC, andreyDelay commented on src/main/java/com/andrey/currencyexchgr/dto/UpdateCurrencyDto.java
> +	private double value;
Добавил

2022-05-10 14:08 UTC, andreyDelay commented on src/main/java/com/andrey/currencyexchgr/service/impl/DataBaseCurrencyServiceImpl.java
>          repository.findAll().forEach(value ->
Исправил, но всё равно приходится мапить объекты

2022-05-10 14:46 UTC, merged